### ISSUE TITLE
Rails 4 version?

### ISSUE THREAD

**Issue by bj-mcduck** [lgs/mongoid_taggable_with_context#13]
I was testing out a Rails 4 app using your mtwc gem and got some errors.

Thought I might try to see if I'm able to migrate it to 4.

I'm newer to Rails and haven't tried helping with an open-source project, but I'm feeling pretty comfortable with Rails now and think it would be fun to try.

You haven't started work on a v4 branch yet have you?

Cheers,
-Brandon

**Comment by johnnyshields** [comment]
@brandonjmckay We haven't attempted to make this plugin work for Rails 4 or Mongoid 4 yet. If you'd like to contribute, please fork the repo, make your changes, make sure all test specs are passing, then raise a pull request--we'll review it once you submit it. Cheers!

**Comment by bj-mcduck** [comment]
I'm a little behind on some things, I haven't been able to start this yet. Just FYI.

**Comment by bj-mcduck** [comment]
Sorry. I've stopped using Mongoid. I'm probably not going to work on this.
