### ISSUE TITLE
Undefined method 'join' for nil:NilClass

### ISSUE THREAD

**Issue by bj-mcduck** [lgs/mongoid_taggable_with_context#14]
While in production, I'm getting the error:

```
NoMethodError (undefined method `join' for nil:NilClass):
```

It seems that when in production it throws this error rather than showing nothing when asking for the `<object>_string` method.

I'm running rails 3.2.8, Mongoid, on Heroku.

**Comment by lgs** [comment]
this is very old, I close it assuming solved/overcome ...
