### ISSUE TITLE
undefined method `tags_with_weight' for

### ISSUE THREAD

**Issue by parthisrm** [lgs/mongoid_taggable_with_context#15]
Getting this error 
undefined method `tags_with_weight' for

I am using  Mongoid::TaggableWithContext::AggregationStrategy::RealTime strategy

tags method works as expected. using Rails 3.2.13, Mongoid 3.0.23.

The Model / document where I am using tags is embedded in another document.

class Note
  include Mongoid::Document
  include Mongoid::Timestamps
  include Mongoid::TaggableWithContext  
  include Mongoid::TaggableWithContext::AggregationStrategy::RealTime  

  taggable

  field :name, type: String
  field :content, type: String

  embedded_in :root, :inverse_of => :notes
end

**Comment by lgs** [comment]
Did you included an aggregation strategy ? ... something like: 

<pre>
class Post
  include Mongoid::Document
  include Mongoid::TaggableWithContext
  # automatically adds real time aggregations to all tag contexts
  include Mongoid::TaggableWithContext::AggregationStrategy::RealTime
  # alternatively for map-reduce
  # include Mongoid::TaggableWithContext::AggregationStrategy::MapReduce
  field :title
  field :content
  taggable
  taggable :skills, separator: ','
  taggable :ints, as: interests
end
</pre>

When you include an aggregation strategy, your document also gains a few extra methods to retrieve aggregation data. In the case of previous example the following methods are included:

<pre>
Post.tags
Post.tags_with_weight
Post.interests
Post.interests_with_weight
Post.skills
Post.skills_with_weight
</pre>
