### ISSUE TITLE
Localize is not working fine

### ISSUE THREAD

**Issue by hyperrjas** [lgs/mongoid_taggable_with_context#6]
```
class Instrument
  include Mongoid::Document
  include Mongoid::Timestamps
  include Mongoid::TaggableWithContext
  include Mongoid::TaggableWithContext::AggregationStrategy::RealTime

  #taggable
  taggable :separator => ', ', localize: true

  #fields
  field :title, :type => String, localize: true
  field :description, :type => String, localize: true
  #
  #
  #
end
```

Localize is working fine with field  `title`, however I can not see `tags` or `tags_string` as a localized field.

I can see in my console:

`=> #<Instrument _id: 516fccf9a616544417000001, created_at: 2013-04-18 10:37:45 UTC, updated_at: 2013-04-18 10:37:45 UTC, tags: ["accordion", "accordion1", "accordion2"], title: {"en"=>"Accordion"}, description: {"en"=>"accordion description"}>`

How can I fix this issue?

Thanks!

**Comment by johnnyshields** [comment]
@hyperrjas I've enabled the :localize option to pass-thru to Mongoid in my fork https://github.com/johnnyshields/mongoid_taggable_with_context and raised pull request #8 

However, be aware the localize is **not** a deep localize of each tag value, rather, just applies at the array level. So the tag values for different locales may be out-of-sync, e.g.:

```
tags #=> { en: ['cat','dog','fish'], fr: ['tag1'] }
```

**Comment by johnnyshields** [comment]
Pull request #8 is merged... please try it.

**Comment by lgs** [comment]
pull request #9 is merged too ...

**Comment by johnnyshields** [comment]
@lgs can you make me a repo collaborator so I can close issues (like this one?)

**Comment by johnnyshields** [comment]
@hyperrjas going to close this issue. `localize: true` is possible now in v 1.1.2, however, please be aware of the "shallow-localize" limitation described above.

**Comment by lgs** [comment]
@johnnyshields   ... I just add you on rubygems owners list,  as well. 

See: https://rubygems.org/gems/mongoid_taggable_with_context

**Comment by johnnyshields** [comment]
Cheers, thank you!

**Comment by hyperrjas** [comment]
thank you!!! :)
